### ISSUE TITLE
Risk Assesment Suggestions / Checklist

### ISSUE THREAD

**Issue by Tanner-Ray-Martin** [pybites/rust-bite-exercises#15]
#### 1. **Prohibited Patterns (Rust code review)**
Update the `prohibited_patterns` list to cover more potentially dangerous activities:

```python
prohibited_patterns = [
    r"std::fs",  # Filesystem access
    r"std::net",  # Networking
    r"extern crate",  # External crate injection
    r"Command::new",  # Shell or command execution
    r"std::process",  # Process control
    r"unsafe",  # Unsafe blocks
    r"env::",  # Access to environment variables
    r"thread::spawn",  # Thread creation (potential DoS vector)
    r"std::time::sleep",  # Long sleeps (possible DoS attack)
]
```

#### 2. **Docker Configuration**
Here’s a sample Docker configuration for running your code validator securely.

##### Dockerfile
```Dockerfile
FROM rust:latest

# Create a non-root user
RUN addgroup --system rustuser && adduser --system --ingroup rustuser rustuser

# Set the working directory
WORKDIR /home/rustuser

# Set the non-root user for execution
USER rustuser

# Copy code and set permissions
COPY . .

# Install any dependencies if needed (e.g., Rust tools, validators)
RUN cargo install --path .

# Disable networking
CMD ["--network", "none"]

# Set resource limits in Docker to prevent DoS attacks
CMD ["--memory", "256m", "--cpus", "1.0"]
```

#### 3. **Security Measures for Docker Container**
- Ensure containers run with **no additional privileges**:
    ```bash
    docker run --cap-drop=ALL --security-opt=no-new-privileges
    ```
- Disable network access within containers unless strictly needed:
    ```bash
    docker run --network none
    ```
- Use a **non-root user** inside the Docker container:
    - This limits permissions within the container, even if compromised.

#### 4. **Timeout and Resource Constraints**
- Add a **timeout** for running user-submitted code to prevent infinite loops:
    - Python Example:
    ```python
    import subprocess
    subprocess.run(["rust_test_binary"], timeout=5)  # 5-second timeout
    ```
- Set resource limits on Docker container execution:
    ```bash
    docker run --memory="256m" --cpus="1.0"
    ```

---

### Additional Security Checks (Checklist)

- [ ] **Scan for Suspicious Macros**:
    - Check for complex macros that might hide malicious code.
    - Example:
    ```bash
    grep -E -r 'macro_rules!' ./src
    ```

- [ ] **Monitor Rust Crates for Prohibited Imports**:
    - Perform a scan for unsafe or dangerous imports (e.g., unsafe code).
    - Example:
    ```bash
    grep -E -r 'unsafe' ./src
    ```

- [ ] **Handle Infinite Loops**:
    - Implement a **timeout mechanism** on user code execution (e.g., 5 seconds).
    - Python Example:
    ```python
    import subprocess
    subprocess.run(["rust_program"], timeout=5)
    ```

- [ ] **Set Docker Resource Constraints**:
    - Set memory and CPU limits on containers.
    - Example:
    ```bash
    docker run --memory="256m" --cpus="1.0"
    ```

- [ ] **Restrict File Permissions**:
    - Ensure containers don’t have unnecessary access to file systems.
    - Docker flags:
    ```bash
    --read-only
    ```

- [ ] **Ensure Regular Docker Image Updates**:
    - Keep the Docker base image and dependencies up-to-date with security patches.

- [ ] **Disable Shell Access**:
    - Avoid giving access to `sh` or `bash` from within the container to avoid shell injection attacks.
    - Prohibited pattern:
    ```python
    r"/bin/sh"
    ```

**Comment by Tanner-Ray-Martin** [comment]
Here’s a comment you can post on the GitHub issue to explain your findings regarding the `long_sleep` test:

---

### Issue: Long Sleep Test Behavior

I ran the `try_long_sleep()` function, which introduces a 10-second sleep, and here’s what I observed:

- The test successfully waits for the full 10 seconds, confirming that this duration works without causing issues.
- However, when increasing the sleep time to 60 seconds, the test results in a **timeout error**.
  
  **Current Code:**

```rust
use std::thread;
use std::time::Duration;

fn hello_world() -> String {
    "Hello, World!".to_string()
}

pub fn try_long_sleep() {
    thread::sleep(Duration::from_secs(10)); // Works fine for 10 seconds
    println!("Finished long sleep!");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world() {
        assert_eq!(hello_world(), "Hello, World!");
    }

    #[test]
    fn test_long_sleep() {
        let result = std::panic::catch_unwind(|| try_long_sleep());
        assert!(result.is_err(), "Long sleep was not blocked!");
    }
}
```

**Test Result (for 10 seconds sleep):**

```txt
running 2 tests
test tests::test_hello_world ... ok
test tests::test_long_sleep ... FAILED

failures:

---- tests::test_long_sleep stdout ----
Finished long sleep!
thread 'tests::test_long_sleep' panicked at src/main.rs:28:9:
Long sleep was not blocked!
```

### Observations:

1. **10-Second Sleep**: The test successfully completes after the 10-second sleep, indicating that no issues occur within this duration.
2. **60-Second Sleep**: When increasing the sleep duration to 60 seconds, the test fails due to a **timeout error**.
   
### Potential Issue:
I'm not entirely sure whether the test continues running in the background after the timeout occurs. It would be helpful to confirm whether the background thread/process is properly killed once the timeout is triggered.

This suggests that:
- For a sleep duration of up to 10 seconds, the system behaves as expected, and the thread sleep operates.
- For longer durations (e.g., 60 seconds), a timeout is triggered, but further investigation is needed to ensure the process isn’t still running in the background after the test timeout.


---

**Comment by Tanner-Ray-Martin** [comment]
Unsure if this matters (as long as we can put a limiter somewhere). We may want to create bites that use threads.
---

### Issue: Thread Creation Test Behavior

I ran the `try_thread_creation()` function, which spawns a new thread that prints a message and sleeps for 500 milliseconds repeatedly. Here’s what I observed during the test:

- The test **creates 20 threads** successfully, and they complete as expected.
- However, the test **fails** with the assertion `Thread creation was not blocked!` indicating that thread creation itself was not prevented by the current settings.

**Current Code:**

```rust
use std::thread;
use std::time::Duration;

fn hello_world() -> String {
    "Hello, World!".to_string()
}

pub fn try_thread_creation() {
    let handle = thread::spawn(|| {
        for _ in 0..20 {
            println!("Thread created!");
            thread::sleep(Duration::from_millis(500));
        }
    });

    handle.join().expect("Thread joining failed!");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world() {
        assert_eq!(hello_world(), "Hello, World!");
    }

    #[test]
    fn test_thread_creation() {
        let result = std::panic::catch_unwind(|| try_thread_creation());
        assert!(result.is_err(), "Thread creation was not blocked!");
    }
}
```

### Test Result:

```txt
running 2 tests
test tests::test_hello_world ... ok
test tests::test_thread_creation ... FAILED

failures:

---- tests::test_thread_creation stdout ----
Thread created!
Thread created!
...
Thread created!
thread 'tests::test_thread_creation' panicked at src/main.rs:34:9:
Thread creation was not blocked!
```

### Observations:

1. **Thread Creation**: The threads are successfully created and joined, which suggests that thread spawning is currently **not restricted** by the settings. This could potentially allow for Denial of Service (DoS) attacks if excessive threads are created.
   
2. **Assertion Failure**: The test fails with the message `Thread creation was not blocked!`, confirming that the system allowed thread creation to proceed.

### Potential Issue:
This behavior highlights a potential risk where unmonitored thread creation could lead to resource exhaustion. Threads are created and completed, but without proper limits, an attacker could create an excessive number of threads, leading to a DoS scenario.

### Suggested Action:
- Consider enforcing limits on thread creation within the validator environment, or disallowing certain thread-related functionality to prevent potential misuse.

---
